# nixpacks.toml configuration file
# Custom install phase to fallback to npm install if npm ci fails

[phases.install]
# Override default install command
# Use bash -c to execute conditional command: try npm ci, if it fails then run npm install
cmds = ["bash -c 'npm ci || npm install'"]
