# nixpacks.toml configuration file
# Custom install phase to directly use npm install instead of npm ci

[phases.install]
# Override default install command
# Directly use npm install to avoid package-lock.json sync issues
cmds = ["npm install"]
